filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'
Plugin 'altercation/vim-colors-solarized.git'

call vundle#end()            " required
filetype plugin indent on    " required

let vimrplugin_r_path = "/homes/tl344/tom/bin/bobR.sh"

" Remap autocompletion to ctrl-space
inoremap <Nul> <C-n>

imap jj <Esc>

" Remap SendSelection and Sendline to Leader-Space
vmap <Space> <Plug>RDSendSelection
nmap <Space> <Plug>RDSendLine

" Set local leader
set backspace=indent,eol,start

let maplocalleader = "\\"
" Disable the automatic replacement of _ with <- This is to avoid problems
" when pasting code that contains _
let vimrplugin_assign = 0

set hlsearch
set nu
" Highlight search pattern as you type
set incsearch

" If you press enter after a search the search pattern is cleared
nnoremap <CR> :noh<CR><CR>
" invoke as :call Movl(start, end)
function Movl (start, end)
    let s = a:start
    let e = a:end
    normal mp
    exe s.','.e.'d' 
    normal 'p
    normal p
endfunction

" Makes mouse scrolling and selecting work
set mouse=a
" This line solves the problem of clicks past the 220th column not being
" caught
set ttymouse=sgr

" Solarized color theme
syntax enable
set background=dark
let g:solarized_termtrans=1
"set t_Co=16
colorscheme solarized


" Disable the arrows so that i stick my hands to the home row
 noremap   <Up>     <NOP>
 noremap   <Down>   <NOP>
 noremap   <Left>   <NOP>
noremap   <Right>  <NOP>
